/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package social.multiplication.domain;

import org.junit.Test;
import static org.junit.Assert.*;

public class MultiplicationServiceTest {
	
    @Test public void testSomeLibraryMethod() {
        Multiplication classUnderTest = new Multiplication();
    }
}
