/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package social.multiplication.domain;

import lombok.Getter;

@Getter
public class Multiplication {
	
	private int factorA;
	private int factorB;
	

}
